name: Update Nuclei Templates

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  update-nuclei-templates:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download templates
        run: git clone https://github.com/projectdiscovery/nuclei-templates.git config

      - run: |
        git add config/
        git config --local user.email "18237644+amocsub@users.noreply.github.com "
        git config --global user.name "amocsub"
        git diff-index --quiet HEAD || git commit -m "${{ github.workflow }} - Run ${{ github.run_id }}" --allow-empty
        git push -f
